# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ScladTov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srokmes', models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default=('1', '01'), max_length=1)),
                ('srokgod', models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021'), ('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025')], default=('20', '2020'), max_length=1)),
                ('kol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sclad.Category')),
            ],
        ),
        migrations.AddField(
            model_name='scladtov',
            name='tovars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sclad.Tovar'),
        ),
    ]
