# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scladtov',
            name='srokgod',
            field=models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021'), ('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025')], default=('20', '2020'), max_length=2),
        ),
        migrations.AlterField(
            model_name='scladtov',
            name='srokmes',
            field=models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('8', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default=('1', '01'), max_length=2),
        ),
    ]
