# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0003_auto_20171010_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scladtov',
            old_name='tovars',
            new_name='mytovars',
        ),
    ]
