# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0004_auto_20171011_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='scladtov',
            name='myuser',
            field=models.CharField(default='Kate', editable=False, max_length=120),
        ),
    ]
