# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0005_scladtov_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scladtov',
            name='srokgod',
            field=models.CharField(choices=[('18', '2018'), ('19', '2019'), ('20', '2020'), ('21', '2021'), ('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025'), ('26', '2026'), ('27', '2027'), ('28', '2028'), ('29', '2029'), ('0', '-')], default=('20', '2020'), max_length=2),
        ),
    ]
