# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0007_auto_20171204_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scladtov',
            name='myuser',
            field=models.CharField(default='', max_length=120),
        ),
    ]
