# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sclad', '0009_auto_20171207_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scladtov',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
